---
title: "Random"
author: "km"
date: "2019/7/19"
output: 
  html_document: 
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(reticulate)
python_env <- "/Users/km/python/test/.venv/bin/python"

use_python(python = python_env, required = TRUE)
```


## uniform distribution

### in R

```{r}
seed <- 71
N <- 100000

unif_R <- runif(N)

unif_R %>% head(10)
unif_R %>% mean()
```


### in Numpy

```{python}
import numpy as np

seed = int(r.seed)
N = int(r.N)

np.random.seed(seed=seed)
unif_np = np.random.rand(N)

unif_np[:10]
np.mean(unif_np)
```

### in python random

```{python}
import random

random.seed(seed)

unif_rd = np.array([random.random() for i in range(N)])

unif_rd[:20]
```


### in R

```{r}
seed <- 71
N <- 100000

rd <- import("random")
rd$seed(seed)
unif_R <- map_dbl(1:N, ~rd$random())
```


### in python random

```{python}
import random
N = int(r.N)
seed = int(r.seed)

random.seed(seed)
unif_P = np.array([random.random() for i in range(N)])
```

```{r}
pyenv <- import_main() 
unif_P <- pyenv$unif_P

sum(unif_R - unif_P)
```